# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mobileprice?useSSL=false&serverTimezone=UTC
spring.datasource.username=springuser
spring.datasource.password=thepassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Specify the Hibernate dialect storage engine to use InnoDB
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

# MVC Path Matching Strategy
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# Management Endpoints Configuration
management.endpoints.web.exposure.include=health, beans, metrics
management.endpoints.web.base-path=/management-dashboard
management.endpoint.health.show-details=always

# Custom Service Configuration
dummyService.port=8081
dummyService.address=127.0.0.1
